### PR TITLE
[fix] ter-indent issue (resolve #275)

### LINKED ISSUE #275: [ter-indent] not work with some comments
➜  tslint-eslint-rules git:(master) ✗ npx tslint --version
5.7.0
➜  tslint-eslint-rules git:(master) ✗ npx tsc --version
Version 2.5.3

Run this test case:

````js
ruleTester.addTestGroup('indent-number', 'should force a certain indentation number', [
  {
    code: dedent`
    /**
     * test
     * @param {Object | Immutable.Record(File)} file
     * @param {String} type
     */
    export const test = (file: any = {}, type) => {
      //
    }`,
    options: [2]
  }
])
````

The result is:

```
ter-indent: Expected indentation of NaN spaces but found 0.
```

When we remove the function comments, this test works fine.

### PR DESCRIPTION
**Pull request by ekoneko**

### CODE REVIEW

File: src/rules/terIndentRule.ts [hunk 1]
```diff
@@ -1085,7 +1085,7 @@ class IndentWalker extends Lint.RuleWalker {
     } else {
       const nodeIndent = this.getNodeIndent(node).goodChar;
       const varKind = node.getFirstToken().getText();
-      const elementsIndent = nodeIndent + indentSize * OPTIONS.VariableDeclarator[varKind];
+      const elementsIndent = nodeIndent + indentSize * (OPTIONS.VariableDeclarator[varKind] || DEFAULT_VARIABLE_INDENT);
```
Comment (jmlopez-rod) [inline src/rules/terIndentRule.ts]: Makes sense only in the case when `(OPTIONS.VariableDeclarator[varKind]` is undefined. But what about when we explicitly say that it should be zero? I think a better solution would be to modify the if statement in line 238:

```
OPTIONS.VariableDeclarator = {
          var: userOptions.VariableDeclarator,
          let: userOptions.VariableDeclarator,
          const: userOptions.VariableDeclarator
        };
```

We need to make sure that if `userOptions.VariableDeclarator` not a number then to set it to the default. Can you check if this would still work with your test?

Comment (ekoneko) [reply src/rules/terIndentRule.ts]: @jmlopez-rod `userOptions.VariableDeclarator` has default value yet.
I found the `varKind` is `export` (in my test), so `OPTIONS.VariableDeclarator[varKind]` is undefined.
Maybe best way is to find the correct varKind, but I'm not good at AST parser.
And you are right I should consider userOptions.VariableDeclarator is zero
