### PR TITLE
[bug] fixed brace-style rule (closes #93)

### LINKED ISSUE #93: brace-style error when try/finally block is missing a catch block
The brace-style rule throws when it encounters a `try`/`finally` block with no `catch`, e.g.
```
try {
  // do some stuff here
} finally {
  // clean-up code here
}
```
Adding the `catch` block fixes the problem.

The error is something like:

```
/node_modules/tslint-eslint-rules/dist/rules/braceStyleRule.js:130
        return node.getSourceFile().getLineAndCharacterOfPosition(node.getEnd());
                   ^

TypeError: Cannot read property 'getSourceFile' of undefined
    at BraceStyleWalker.getEndPosition (/node_modules/tslint-eslint-rules/dist/rules/braceStyleRule.js:130:20)
    at BraceStyleWalker.areOnSameLine (/node_modules/tslint-eslint-rules/dist/rules/braceStyleRule.js:124:21)
    at BraceStyleWalker.visitTryStatement (/node_modules/tslint-eslint-rules/dist/rules/braceStyleRule.js:65:40)
    at BraceStyleWalker.SyntaxWalker.visitNode (/node_modules/tslint/lib/language/walker/syntaxWalker.js:429:22)
    at /node_modules/tslint/lib/language/walker/syntaxWalker.js:459:63
```

### PR DESCRIPTION
**Pull request by hadalin**
This will fail until https://github.com/buzinas/tslint-eslint-rules/pull/101 is merged. `brace-style` tests pass (at least locally 😄).

### CODE REVIEW

File: src/test/rules/braceStyleRuleTests.ts [hunk 1]
```diff
@@ -246,8 +422,8 @@ describe(rule, function test() {
   const onetbsConfig = { rules: { 'brace-style': [true, '1tbs'] } };
   const stroustrupConfig = { rules: { 'brace-style': [true, 'stroustrup'] } };
   const allmanConfig = { rules: { 'brace-style': [true, 'allman'] } };
-  const onetbsConfigWithException = { rules: { 'brace-style': [true, 'stroustrup', { allowSingleLine: true }] } };
-  const stroustrupConfigWithException = { rules: { 'brace-style': [true, '1tbs', { allowSingleLine: true }] } };
+  const onetbsConfigWithException = { rules: { 'brace-style': [true, '1tbs', { allowSingleLine: true }] } };
```
Comment (hadalin) [inline src/test/rules/braceStyleRuleTests.ts]: There was also a bug in tests.

File: src/rules/braceStyleRule.ts [hunk 2]
```diff
@@ -148,4 +161,17 @@ class BraceStyleWalker extends Lint.RuleWalker {
   private getEndPosition(node: ts.Node) {
     return node.getSourceFile().getLineAndCharacterOfPosition(node.getEnd());
   }
+
+  // returns previous node which is either block or catch clause (no keywords, etc).
+  private getPreviousNode(children: ts.Node[], node: ts.Node): ts.Node {
+    let position = children.indexOf(node) - 1;
+    while (position >= 0) { // is first child always block or catch clause?
```
Comment (jmlopez-rod) [inline src/rules/braceStyleRule.ts]: hi @hadalin, for readability purposes would you mind refactoring this method so that there are no variable declarations inside the loop? You can also get rid of the `else` block and simply decrease the `position`.

**Comment by jmlopez-rod** [comment]
This PR seems sound. Good catch on the test bug.
