### PR TITLE
[fix] differentiate method from variable (closes #153)

### LINKED ISSUE #153: handle-callback-err: does not differentiate method from variable
In the following error handling:

`error => console.error('Could not print the document');`

The error is not thrown because of console.**error**. But it should since the actual error variable is not handled.

relevant tslint config: {"handle-callback-err": [true, "^(err|error)$"]}

tslint: 4.0.2
tslint-eslint-rules: 3.2.0
typescript: 2.1.4
vscode: 1.7.2
vscode-tslint: 0.7.1

### PR DESCRIPTION
**Pull request by jmlopez-rod**

### CODE REVIEW

File: src/test/rules/handleCallbackErrRuleTests.ts [hunk 1]
```diff
@@ -86,7 +91,35 @@ ruleTester.addTestGroup('custom-error-name-pass', 'should pass with custom error
...
+    options: ['error'],
+    errors: [error]
+  },
+  {
+    code: `error => something.something.error.something.err('Could not print the document');`,
+    options: ['^(err|error)$'],
+    errors: [error]
+  },
+  {
+    code: `error => console.error(error.stack);`,
```
Comment (fxlemire) [inline src/test/rules/handleCallbackErrRuleTests.ts]: I think this should pass since allowProperties is not set to true?

File: src/test/rules/handleCallbackErrRuleTests.ts [hunk 2]
```diff
@@ -86,7 +91,35 @@ ruleTester.addTestGroup('custom-error-name-pass', 'should pass with custom error
...
+    options: ['^(err|error)$', { allowProperties: false }],
+    errors: [strictError]
+  },
+  {
+    code: 'var test = err => err.message;',
+    options: ['err', { allowProperties: false }],
+    errors: [strictError]
+  },
+  {
+    code: `error => error ? console.error(error.stack) : console.log('no error');`,
```
Comment (fxlemire) [inline src/test/rules/handleCallbackErrRuleTests.ts]: I think this should also pass since if `error` doesn't exist, it has been handled, and if it exists, it is handled fine since allowProperties is not set to false.

File: src/test/rules/handleCallbackErrRuleTests.ts (hunk 1 above)
Comment (jmlopez-rod) [inline src/test/rules/handleCallbackErrRuleTests.ts]: It passes, notice that this test does not expect any `errors` like the next one.

```
{
     code: `error => console.error(error.stack);`,
     options: ['^(err|error)$', { allowProperties: false }],
     errors: [strictError]
   },
```

The one expects the strict error since the allow properties is turned off.

File: src/test/rules/handleCallbackErrRuleTests.ts [hunk 3]
```diff
@@ -86,7 +91,35 @@ ruleTester.addTestGroup('custom-error-name-pass', 'should pass with custom error
...
+    options: ['^(err|error)$']
+  }
```
Comment (fxlemire) [inline src/test/rules/handleCallbackErrRuleTests.ts]: How would we handle the above example with `allowProperties: false` in case the error exists?

Comment (jmlopez-rod) [inline src/test/rules/handleCallbackErrRuleTests.ts]: If we put the option to false it would still work since the callback has `error` in the function body by itself.

File: src/docs/rules/handleCallbackErrRule.md [hunk 4]
```diff
@@ -32,6 +32,14 @@ regexp pattern.
...
   `anyError`, `some_err` will match).
 
+In addition to the string we may specify an options object with the following property:
+
+- `allowProperties`: (`true` by default) When this is set to `false` the rule will not
+  report unhandled errors as long as the error object is handled without accessing any of its
+  properties at least once. For instance, `(err) => console.log(err.stack)` would report an
+  issue when `allowProperties` is set to `false` because `err` is not handled on its
+  own.
+
```
Comment (fxlemire) [inline src/docs/rules/handleCallbackErrRule.md]: I would take the opportunity to add the new object as part of the examples, say on line 50:

`"handle-callback-err": [true, "^(err|error|anySpecificError)$", {"allowProperties": false}]`

Comment (jmlopez-rod) [inline src/docs/rules/handleCallbackErrRule.md]: Done, I think that's it then. I'll merge and do a release sometime tonight. Thanks for your help.

Comment (fxlemire) [inline src/docs/rules/handleCallbackErrRule.md]: Don't thank me, thanks to you!! Great work buddy!

File: src/rules/handleCallbackErrRule.ts [hunk 5]
```diff
@@ -67,10 +80,21 @@ class ErrCallbackHandlerWalker extends Lint.RuleWalker {
...
+    const opt = this.getOptions();
+    let errorArgument = 'err';
+    let optObj = opt[0];
+    if (typeof opt[0] === 'string') {
+      errorArgument = opt[0];
+      optObj = opt[1];
+    }
+
+    if (optObj) {
+      this.allowProperties = !!optObj.allowProperties;
```
Comment (blakeembrey) [inline src/rules/handleCallbackErrRule.ts]: Instead of doing this check, I'd recommend using `this.allowProperties = optObj.allowProperties !== false` as an empty object would equal `false` right now which is inconsistent with non-existence.
